import { Inter } from "next/font/google"
import "./globals.css"
import Provider from "./(components)/Provider"
import Navigation from "./(components)/Navigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
      <Provider>
        <div className='main'>
          <div className='gradient' />
        </div>

        <main className='app'>
          {children}
        </main>
      </Provider>
      </body>
    </html>
  )
}

export default Layout
