import { Inter } from "next/font/google"
import "./globals.css"
import Provider from "./(components)/Provider"
import Navigation from "./(components)/Navigation"
import Footer from "./(components)/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Layout = ({ children }) => {
  return (
    <html lang="en" className="bg-slate-200">
      <body>
      <Provider>
        <div className='main'>
          <div className='gradient' />
        </div>
        <div className="flex flex-col min-h-screen">
          <main className='app'>
              {children}
          </main>
        </div>
      </Provider>
      </body>
    </html>
  )
}

export default Layout
